<?php
	$this->title = "Deletar ocorrência";
	$this->headTitle($this->title);
?>

<div class="callout callout-danger">
                                        <h4>Atenção!</h4>
                                        Deseja realmente deletar  '<?php echo $this->escape($this->ocorrencia['descricao']);?>' Código '<?php echo $this->escape($this->ocorrencia['id_ocorrencia']);?>'?
                                    </div>
<form action="<?php echo $this->url(array('action' => 'lista-ocorrencia'),null, true);?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $this->ocorrencia['id_ocorrencia'];?>" /> 
		
	</div>
	<div class="form-group">
                                        		
<input type="submit" class="btn btn-primary" id="submitbutton" name="del" value="Sim">                                        		
<input type="submit" class="btn btn-primary"   id="vincularReferencia" name="del" value="Não">                                        		

                                    		</div>
</form>
