<?php
	$this->title = "Deletar usuário";
	$this->headTitle($this->title);
?>
<p>Deseja realmente deletar  '<?php echo $this->escape($this->usuarios['nome']);?>' email '<?php echo $this->escape($this->usuarios['email']);?>'?</p>

<form action="<?php echo $this->url(array('action' => 'lista-usuario'));?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $this->usuarios['id_usuario'];?>" /> 
		<input type="submit" name="del" value="Yes" /> <input type="submit" name="del" value="No" />
	</div>
</form>
<div style="width:100%;float:left;"><?php  echo $this->mensagem?></div>