<?php
	$this->title = "Listar Fornecedores";
	$this->headTitle($this->title);
	//echo $this->form ;
	
?>
<div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Lista Fornecedores</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive">                                
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Cód. Fornecedor</th>
                                                <th>Fornecedor</th>
                                                <th>Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php if($this->listaFornecedor>0){
                                        foreach ($this->listaFornecedor as $value){
                                        ?>
                                            <tr>
                                                <td><?php echo $value["codFornecedor"]?></td>
                                                
                                                <td><?php echo $value["nomFornecedor"]?></td>
                                                <td>
                                                 <a alt="Editar" title="Editar" href="<?php echo $this->url(array('controller'=>'index','action'=>'edit-fornecedor', 'id'=>$value["idFornecedor"]),null, true);?>" class="btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a> 
                                                 <a alt="Excluir" title="Excluir" href="<?php echo $this->url(array('controller'=>'index','action'=>'delete-fornecedor', 'id'=>$value["idFornecedor"]),null, true);?>" class="btn-sm  btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
                                                
                                                </td>
                                            </tr>
                                          <?php }}?> 
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                 <th>Cód. Fornecedor</th>
                                                <th>Fornecedor</th>
                                                <th>Ação</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <div class="form-group">
                                 <a alt="Adicionar" title="Adicionar" style="font-family: inherit;" href="<?php echo $this->url(array('controller'=>'index','action'=>'add-fornecedor'),null, true);?>" class="btn-sm  "><i class="btn btn-primary">Adicionar Fornecedor</i></a>   		
                                     		

                                    		</div>
<link href="<?php echo $this->baseUrl()?>/css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl()?>/js/plugins/datatables/jquery.dataTables.js" ></script>
<script src="<?php echo $this->baseUrl()?>/js/plugins/datatables/dataTables.bootstrap.js" ></script>
<!-- page script -->
<script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
                $('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
</script>
