<?php
	$this->title = "Upload arquivos FTP";
	$this->headTitle($this->title);
	//
	
?>
<div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Upload arquivos FTP</h3>
                                </div><!-- /.box-header -->
                                <div class="form-group">
                                
                                </div>
</div>


<div class="row">
                            <div class="col-xs-12">
                            <div class="box box-solid">
                                <div class="box-header">
                                    <h3 class="box-title"></h3>
                                   
                                </div><!-- /.box-header -->
                                <div id="myBody" class="box-body">
                                    <div class="row">
                                        <div class="col-sm-6">
                                          
                                        	<div class="form-group">
                                        	<?php echo $this->form ;?>
                                    		</div>
                                        </div><!-- /.col -->
                                        <div class="col-sm-6">
                                            
                                            
                                        </div><!-- /.col -->
                                    </div><!-- /.row -->
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                        </div>