
<div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                             <form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Detalhes Produto</h3>
                                    <div class="box-tools pull-right">
                                        <button data-widget="collapse" class="btn btn-primary btn-sm" type="button"><i class="fa fa-minus"></i></button>
                                       
                                    </div>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                               
                                
                                     <?php echo $this->element->id_produto; ?>
                                     <?php echo $this->element->nomeImagem; ?>
                                      <?php echo $this->element->id_referencia; 
                                      
                                      //Zend_Registry::get('logger')->log($this->element->nome->getAttrib(), Zend_Log::INFO);
                                      ?>
                                    
                                    <div class="box-body">
                                    
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Nome</label>
                                           <?php echo $this->element->nome; ?>
                                        </div>
                                        <div class="form-group">
                                           
                                           
                                       <?php echo $this->element->fk_fornecedor; ?>
                                       </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Descrição</label>
                                           
                                       <?php echo $this->element->descricao; ?>
                                        		
                                           
                                        </textarea>                       
                                    	
                                           
                                        </div>
                                        <div class="form-group">
                                            <div class="checkbox">
                                                 
                                                <?php echo $this->element->palavrachave; ?>
                                                
											
                                            </div>
                                          </div>
                                        </div><!-- /.box-body -->
									
                                
                            </div><!-- /.box -->
							<div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Refêrencia</h3>
                                    
                                </div><!-- /.box-header -->
                                  <div class="box-body">
                                	<div class="form-group">
                                            <div class="checkbox">
                                                 <label>
                                                <?php echo $this->element->disponivel; ?>
                                                <?php echo $this->element->disponivel->getLabel(); ?>
												</label>
                                            </div>
                                	</div>
                                	<div class="form-group">
                                            <div class="checkbox">
                                                <label>
                                                <?php echo $this->element->ativo; ?>
                                                <?php echo $this->element->ativo->getLabel(); ?>
												</label>
                                            </div>
                                     </div>
                                     <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title" >Adicionar características</h3>
                                    <div class="box-tools pull-right">
                                        <button data-widget="collapse" class="btn btn-primary btn-sm" type="button"><i class="fa fa-minus"></i></button>
                                       
                                    </div>
                                 </div><!-- /.box-header --> 
                                 <div class="box-body"> 
                                    <div class="row">
                                        <div class="col-lg-6">
                                         <label for="exampleInputEmail1">Característica do produto (marca, modelo, tamanho, etc) </label>
                                            <div class="form-group">
                                           
                                                <span class="form-group">
                                                <!--   <input type="text" class="form-control" value="" name="nomecaract"  id="nomecaract">-->
                                                   
                                                    <?php echo $this->element->nomecaract; ?>
                                                </span>
                                               
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                        <div class="col-lg-6">
                                         <label for="exampleInputEmail1">Valor referente à característica do produto (azul, pequeno)</label>
                                            <div class="form-group">
                                                <span class="form-group">
                                               
                                                    <?php echo $this->element->valorcaract; ?>
                                                </span>
                                                
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    </div><!-- /.row -->
                                    <div class="form-group">
                                        
                                        <?php  echo $this->element->adicionarCaract;
                                         
                                        
                                        ?>
                                    </div>
                                </div>
                                <div class="box-body no-padding">
                                    <table class="table table-striped table-bordered" id="tabelaCaracteristicas">
                                        <tr>
                                            <th>Nome</th>
                                            <th>Valor</th>
                                            <th style="width: 40px">Ação</th>
                                            <?php 
                                            
                                            if($this->element->nomeCaracteristica->getValue()>0){
                                            	$i=0;
                                            	$valorArray=$this->element->valorCaracteristica->getValue();
                                            foreach ($this->element->nomeCaracteristica->getValue() as $nome ){
                                            	$valor= $valorArray[$i];
                                            $i++;
                                            	?>	 
                                           
                                            <tr>
	                                            <input type="hidden" value="<?php echo $nome?>" id="nomeCaracteristica" name="nomeCaracteristica[]">
	                                            <input type="hidden" id="valorCaracteristica" name="valorCaracteristica[]" value="<?php echo $valor?>">
	                                            <td><?php echo $nome?></td>
	                                            <td><?php echo $valor?></td>
	                                            <td><a name="deletar" title="deletar" class="del" href="#tabelaCaracteristicas"></a></td>
                                            </tr>
                                            
                                            <?php }}?>
                                            <?php  
                                           
                                            ?>
                                        </tr>
                                        
                                    </table>
                                    <br><br>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <label for="exampleInputEmail1"><?php echo $this->element->precode->getLabel(); ?></label>
                                     <div class="input-group">
                                     	<input type="text" class="form-control" value="<?php echo $this->element->precode->getValue(); ?>" name="<?php echo $this->element->precode->getName(); ?>" id="<?php echo $this->element->precode->getName(); ?>">
                                        <span class="input-group-addon">.00</span>
                                     </div>
                                     <label for="exampleInputEmail1"><?php echo $this->element->precopor->getLabel(); ?></label>
                                     <div class="input-group">
                                     	<input type="text" class="form-control" value="<?php echo $this->element->precopor->getValue(); ?>" name="<?php echo $this->element->precopor->getName(); ?>"  id="<?php echo $this->element->precopor->getName(); ?>">
                                        <span class="input-group-addon">.00</span>
                                     </div>
                                     <label for="exampleInputEmail1"><?php echo $this->element->fretemedio->getLabel(); ?></label>
                                     <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                                        <input type="text" class="form-control" value="<?php echo $this->element->fretemedio->getValue(); ?>" name="<?php echo $this->element->fretemedio->getName(); ?>" id="<?php echo $this->element->fretemedio->getName(); ?>">
                                        <span class="input-group-addon"><i class="fa fa-ambulance"></i></span>
                                    </div>
                                    <div class="form-group">
                                            <label for="exampleInputEmail1"><?php echo $this->element->codigoean->getLabel(); ?></label>
                                            <input type="text" class="form-control" id="codigoean" placeholder="Enter <?php echo $this->element->codigoean->getLabel(); ?>" value="<?php echo $this->element->codigoean->getValue();?>" name="<?php echo $this->element->codigoean->getName(); ?>"> 
                                            
                                   </div>
                                   <div class="form-group">
                                            <label for="exampleInputEmail1"><?php echo $this->element->saldo->getLabel(); ?></label>
                                            <input type="text" class="form-control" id="<?php echo $this->element->saldo->getName(); ?>" placeholder="Enter <?php echo $this->element->saldo->getLabel(); ?>" value="<?php echo $this->element->saldo->getValue();?>" name="<?php echo $this->element->saldo->getName(); ?>"> 
                                            
                                   </div>
                                   <div class="form-group"><div class="btn btn-default"><img src="<?php echo $this->baseUrl()?>/upload/<?php echo $this->element->nomeImagem->getValue();?>" alt="User Image"  width="238" /></div></div>
                                    <div class="form-group"><?php  echo $this->element->fileUpload;?></div>
                                   
                                   
                                </div>
                            </div>
                            <div class="row">
                            <div class="col-xs-12">
                            <div class="box box-solid">
                                <div class="box-header">
                                    <h3 class="box-title"></h3>
                                   
                                </div><!-- /.box-header -->
                                <div class="box-body" id="myBody">
                                    <div class="row">
                                        <div class="col-sm-6">
                                          
                                        	<div class="form-group">
                                        		<?php  echo $this->element->submit;?>
                                        		<?php  echo $this->element->vincularReferencia;?>
                                        		<button style="display: none" type="submit" name="vincularReferencia" id="vincularReferencia" class="btn btn-primary" value="vincular">Vincular Refêrencia</button>
                                    		</div>
                                        </div><!-- /.col -->
                                        <div class="col-sm-6">
                                            
                                            
                                        </div><!-- /.col -->
                                    </div><!-- /.row -->
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                        </div>
                        
                           </form>

                        </div><!--/.col (left) -->
                    </div>   <!-- /.row -->
