
<div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                             <form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
                            
                            
                                        		<?php  echo $this->element->nota_fiscal;?>
                                        		<?php  echo $this->element->cupon_ingresso;?>
                                        	
                        
                           </form>

                        </div><!--/.col (left) -->
                    </div>   <!-- /.row -->