<div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                             <form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Busca Avançada</h3>
                                    <div class="box-tools pull-right">
                                       <button data-widget="collapse" class="btn btn-primary btn-sm" type="button"><i class="fa fa-minus"></i></button> 
                                       
                                    </div>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                               
                                
                                  
                                    <div class="box-body">                                       
                                       <div class="form-group fornecedor">
                                            <?php echo $this->element->fk_fornecedor; ?>
                                       </div>
                                        
                                       <div class="form-group buscadata">
                                        	<?php  echo $this->element->submit;?>
                                       </div>
                                    </div><!-- /.box-body -->
									
                                
                            </div><!-- /.box -->
						
                            
                        
                           </form>

                        </div><!--/.col (left) -->
                    </div>   <!-- /.row -->