
<div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                             <form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Adicionar Ocorrência</h3>
                                    <div class="box-tools pull-right">
                                       <!-- <button data-widget="collapse" class="btn btn-primary btn-sm" type="button"><i class="fa fa-minus"></i></button> -->
                                       
                                    </div>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                               
                                
                                     <?php echo $this->element->id_produto; ?>
                                     <?php echo $this->element->nomeImagem; ?>
                                      <?php echo $this->element->id_referencia; 
                                      
                                      //Zend_Registry::get('logger')->log($this->element->nome->getAttrib(), Zend_Log::INFO);
                                      ?>
                                    
                                    <div class="box-body">
                                    
                                
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Descrição</label>
                                           
                                       <?php echo $this->element->descricao; ?>
                                       </div>
                                        
                                        </div><!-- /.box-body -->
									
                                
                            </div><!-- /.box -->
						
                            <div class="row">
                            <div class="col-xs-12">
                            <div class="box box-solid">
                                <div class="box-header">
                                    <h3 class="box-title"></h3>
                                   
                                </div><!-- /.box-header -->
                                <div class="box-body" id="myBody">
                                    <div class="row">
                                        <div class="col-sm-6">
                                          
                                        	<div class="form-group">
                                        		<?php  echo $this->element->submit;?>
                                        		<?php  echo $this->element->vincularReferencia;?>
                                        		<button style="display: none" type="submit" name="vincularReferencia" id="vincularReferencia" class="btn btn-primary" value="vincular">Vincular Refêrencia</button>
                                    		</div>
                                        </div><!-- /.col -->
                                        <div class="col-sm-6">
                                            
                                            
                                        </div><!-- /.col -->
                                    </div><!-- /.row -->
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                        </div>
                        
                           </form>

                        </div><!--/.col (left) -->
                    </div>   <!-- /.row -->