
<div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                             <form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
                            <div class="box box-primary collapsed-box">
                                <div class="box-header">
                                    <h3 class="box-title">Dados destinatário</h3>
                                    <div class="box-tools pull-right">
                                       <button data-widget="collapse" class="btn btn-primary btn-sm" type="button"><i class="fa fa-minus"></i></button> 
                                       
                                    </div>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                               
                                
                                     <?php //echo $this->element->fk_item; ?>
                                     <?php //echo $this->element->id_item_has_ocorrencia; ?>
                                      <?php //echo $this->element->id_referencia; 
                                      
                                      //Zend_Registry::get('logger')->log($this->element->nome->getAttrib(), Zend_Log::INFO);
                                      ?>
                                    
                                    <div class="box-body" style="display: none;">
                                   
                                        <div class="form-group"><?php echo $this->element->documento; ?></div>
                                        <div class="form-group"><?php echo $this->element->tipopessoa; ?></div>
                                        <div class="form-group"><?php echo $this->element->nome; ?></div>
                                        <div class="form-group"><?php echo $this->element->email; ?></div>
                                        <div class="form-group"><?php echo $this->element->cep; ?></div>
                                        <div class="form-group"><?php echo $this->element->rua; ?></div>
                                        
                                        <div class="form-group"><?php echo $this->element->numero; ?></div>
                                        <div class="form-group"><?php echo $this->element->compl; ?></div>
                                        <div class="form-group"><?php echo $this->element->bairro; ?></div>
                                        <div class="form-group"><?php echo $this->element->cidade; ?></div>
                                        <div class="form-group"><?php echo $this->element->uf; ?></div>
                                        
                                        
                                        <div class="form-group"><?php echo $this->element->ddd; ?></div>
                                        <div class="form-group"><?php echo $this->element->telefone; ?></div>
                                         <div class="form-group"><?php echo $this->element->pontoreferencia; ?></div>
                                          <div class="form-group"><?php echo $this->element->codigoident; ?></div>
                                        </div><!-- /.box-body -->
									
                                
                            </div><!-- /.box -->
						
                        
                           </form>

                        </div><!--/.col (left) -->
                    </div>   <!-- /.row -->