<table width="1000" class="bordasimples" cellpadding="5" cellspacing="0">
	<tr>
		<th>Nome</th>
		<th>url</th>
	
		<th>Ação</th>
	</tr>
	
	<?php if(count($this->listaVideos)>0){
  $class="dif";
  
foreach($this->listaVideos as $video) : ?>
  
  
  <?php
  if($class=="dif")$class="";
  else $class="dif";
  
  	?>
  <tr class="<?php echo $class?>">
		<td>
			<?php echo $this->escape($video["nome"]);?>
		</td>
		<td>
			<?php echo $this->escape($video["url"]);?>
		</td>
		<td>
			<a href="<?php echo $this->url(array('controller'=>'upload','action'=>'edit-video', 'id'=>$video["id"],'idEvento'=>$video["fk_evento"]),null, true);?>">Edit</a>
			<a href="<?php echo $this->url(array('controller'=>'upload','action'=>'delete-video', 'id'=>$video["id"],'idEvento'=>$video["fk_evento"]),null, true);?>">Delete</a>
		</td>
	</tr>
	<?php 
	
	endforeach; ?>
	<?php }
	
	Zend_Registry::get('logger')->log("idEvento".$this->idEvento, Zend_Log::INFO);?>
</table>
<br>
<a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-fotos-evento', 'id'=>$this->idEvento,'videos'=>1),null, true);?>">Voltar</a>

<!--  <a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">Voltar HOME</a>-->